### ISSUE TITLE
Will not install on a project targeting .NET framework 4.5.2

### ISSUE THREAD

**Issue by shoecake** [MountainWarehouse/EasyMWS#32]
As it says above, I tried installing via nuget and it failed with the error:

"Could not install package 'MountainWarehouse.EasyMWS 0.1.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework."

**Comment by shoecake** [comment]
OK, thanks. I will create a new .Net Core project and use that.

**Comment by cazangabriel** [comment]
Glad to help, given that I am writing the documentation at this precise moment, and you can't find any information about how to use the client, here are some bonus raw hints : 
1. queue reports for download with client.QueueReport() as needed,
2. queue feeds for submission with client.QueueFeed() as needed,
3. Call the Poll() method every few minutes (I would recommend making a call every 2 minutes)
4. When a report has been downloaded, or a feed has been submitted, the corresponding callback method provided as parameter for QueueReport / QueueFeed will be invoked.

hope this helps a bit. It's possible I'll post an appropriate readme file / wiki on github by the end of the day.

**Comment by shoecake** [comment]
Great, thanks.
