### ISSUE TITLE
Do some validation around callback method (or allow non-static methods)

### ISSUE THREAD

**Issue by uber-rob** [MountainWarehouse/EasyMWS#7]

**Comment by cazangabriel** [comment]
Just leaving a note for future reference,

As discussed, we could try to add support for non-static method invocation support.
The issue with that is that it won't work out of the box with dependency injection, so we could try to explicitly instantiate classes using constructors with injected parameters.
The instantiation could either be done using instance activator, or.. perhaps we could somehow pass in a reference of the D.I. framework for using it to resolve the dependencies - but.. do this while not introducing a dependency to a specific D.I. implementation - try to stay agnostic.

**Comment by cazangabriel** [comment]
The next major version release will see static method callbacks removed entirely from the client, and replaced with .net events which can be subscribed to get the reports.
