### ISSUE TITLE
Dependency on EF.Core is strange for this library.

### ISSUE THREAD

**Issue by ThreeFold** [MountainWarehouse/EasyMWS#77]
### This is more of  a statement and an ask for the re-evaluation of EF.Core in the core library.

As a library, I find it strange that this has a requirement on EF Core. I feel that if someone wants to be able to use this, and having them be restricted to pulling in EF Core to their project is a huge hindrance to development. I would move this dependency on EF Core to the developer rather than internally reliant on that mechanism. If you need EF Core support and subsequently need to be able to store things to a data store that should be evaluated by the developer and not be thrust upon them because of a specific requirement somewhere else.
#78  demonstrates that you can simply remove EF core and maintain current capability. Now if the tests are not representative, that is something different and needs to be re-evaluated.

**Comment by cazangabriel** [comment]
I agree with you about the disadvantages of forcing a dependency of EF.Core along with this library.

The main reason for which we chose to do this is the benefit of having a persistent state, specifically, being able to resume report downloading or feed uploading in case the hosting server resumes after being unavailable. 

After briefly discussing the idea with my team, we thought a good approach to decoupling the persistence implementation away from the library could be to expose an IPersistenceProvider interface that could have a few implementations like EFPersistenceProvider, MongoDbPersistenceProvider, or InMemoryPersistenceProvider for example; users could also provide their own implementations of this interface to handle persistence in anyway they see fit. Each implementation of IPersistenceProvider could be exposed as an additional NuGet package like EasyMws.Persistence.EntityFramework, and the choice of the provider could be configurable somehow, perhaps in a fluent manner.

I have not looked at the pull request yet, but I hope to do so sometime this week or the next.
Thanks for the suggestion!
p.s. I agree I significant portion of the unit tests are not very useful - they could easily be re-evaluated.

**Comment by ThreeFold** [comment]
I like the approach given by libraries like [FluentFTP](https://github.com/robinrodricks/FluentFTP), where they expose either an "easy-to-use" method for downloading that has checksumming and retry logic or they will just expose the Download stream to you and have you deal with everything else, it just handles the connection logic.

**Comment by cazangabriel** [comment]
this will be handled by https://github.com/MountainWarehouse/EasyMWS/issues/61
