### ISSUE TITLE
Multiple MWS clients one Database

### ISSUE THREAD

**Issue by shoecake** [MountainWarehouse/EasyMWS#81]
I am planning on rolling out my desktop application onto multiple computers. Each instance should run independently of each other. i.e. If an instance requests a report, then it is that instance which should process/display the report.

If the poll event is being run on multiple computers at the same time, does EasyMWS run the callback code on the machine which created the request or would it run on the first machine to call the poll method.

If the code does not support multiple machines at the moment, is there a way or prepending the SQL tables with the machine name at runtime? Or should I look at creating a local  MDF database to create the SQL tables in?

**Comment by cazangabriel** [comment]
Hi, unfortunately the callback code would run on the machine that calls Poll first; this is quite an annoying drawback.
The code does support multiple machines, I coded against db deadlocks as much as I could, but callback invocation behaves in a FCFS manner; there's no way at the moment to restrict callback invocation to a certain client.
At the moment using local MDF files sounds as viable workaround if you really need the functionality you mentioned.

It is possible to add support for the functionality you requested, I have created [this issue](https://github.com/MountainWarehouse/EasyMWS/issues/82) that details how this would be implemented; unfortunately EasyMws is sort of a side project for my company and it doesn't have really high priority compared to the rest of my wor., I guess the changes would take about 1 day of work to implement but I just have to find the time to do it... If you think you could spare some time to make the change yourself, feel free to submit a pull request and ask me questions regarding the implementation.

**Comment by cazangabriel** [comment]
Hello, I implemented the feature you requested, lucky I had a do-whatever-you-want-at-work day :)
The pull-request is still in progress though.

You will be able to force clients to only invoke callbacks for requests that they made, 
by controlling options in this group **EasyMwsOptions.CallbackInvocationOptions.RestrictInvocationToOriginatingInstance** :
1. set ForceInvocationByOriginatingInstance option to true;
2. optionally set CustomInstanceId to an arbitrary identifier of an EasyMwsClient instance (you can also share the same instanceId between multiple clients if you wish). If you don't set CustomInstanceId it will automatically be set to a Hash of Environment.MachineName
3. set AllowInvocationByAnyInstanceIfInvocationFailedLimitReached to false if you ever only want for clients who create requests to invoke their own callbacks. But in case you host the clients on virtual machines which might be recycled, you could set this option to true to allow any other clients to invoke a callback if it fails a given number of times (InvocationFailuresLimit).

Cheers,
Gabriel

**Comment by shoecake** [comment]
Thanks, that is amazing. I hadn’t even found time to look at the code yet.

________________________________

**Comment by cazangabriel** [comment]
Ok, the code is on the Dev branch, you can give it a try if you like - but I would still like to do some manual testing before releasing the new changes; I just have to find the time to do it - it might not be today.

**Comment by cazangabriel** [comment]
We are going to do a major version release in the very near future which will make it much easier to get the reports. Instead of method callbacks we are just going to use .net events. There will be to events to subscribe to on the IEasyMwsClient interface, ReportDownloaded and FeedUploaded.

Unfortunately this will not solve the problem you're having trying to handle each report on the machine that queued it for download. 
Although not trivial, one way to handle the problem could be for you to post reports downloaded on any machine to a single document hub (which could be an API, microservice, etc).

I have a long term plan to decouple the client from Entity Framework and let the user specify their own implementation for the persistence layer (e.g. if using local file system for persistence, that would solve your problem I believe).

**Comment by shoecake** [comment]
I have ended up using a local MDF database as it made sense with some other packages I was using. 
Decoupling from EF would give the most flexibility, especially for a client application which doesn't need any long term persistence (e.g. an in memory or local file implemetation).
